# Search for lines that start with 'X' followed by any
# non whitespace characters and ':' followed by a space
# and any number. The number can include a decimal.
# Then print the number if it is greater than zero.
import re
hand = open('mbox-short.txt')
count=0
for line in hand:
    line = line.rstrip()
    count+=1
    x = re.findall('(^X\S*): [0-9.]+', line)
    if len(x) > 0:
        print(x)
print(count)


#OUTPUT
"""
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
['X-DSPAM-Confidence']
['X-DSPAM-Probability']
"""
