import Docx
doc = docx.Documents()
doc.add_paragraph('Hello world!', 'Title')
doc.add_heading('Header 0', 0)
doc.add_heading('Header 1', 1)
doc.add_paragraph("Hello World")
paraObj1 = doc.add_paragraph('This is a second paragraph.')
paraObj2 = doc.add_paragraph('This is a yet another paragraph.')
paraObj1.add_run(' This text is being added to the second paragraph.')
doc.save('new.docx')
